name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install SQL Server
      uses: Particular/install-sql-server-action@v1.0.0
      with:
        connection-string-env-var: ConnectionStringForTests

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: powershell .\scripts\test.ps1

    - uses: actions/upload-artifact@v3
      with:
        name: SqlServerCoverage.CommandLine.nupkg
        path: out/tool/*.nupkg

    - uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: out/tests

    - name: Nuget Push
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        cd out/tool
        dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $env:NUGET_API_KEY
