name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install SQL Server
      uses: Particular/install-sql-server-action@v1.0.0
      with:
        connection-string-env-var: ConnectionStringForTests
          
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: powershell .\scripts\build.ps1
