name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install SQL Server
      uses: Particular/install-sql-server-action@v1.0.0
      with:
        connection-string-env-var: ConnectionStringForTests
          
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: powershell .\scripts\test.ps1
      
    - uses: actions/upload-artifact@v3
      with:
        name: SqlServerCoverage.CommandLine.nupkg
        path: out/tool/*.nupkg

    - uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: out/tests

    - name: Nuget Push
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ secrets.nuget_api_key }}
      run: dotnet nuget push out/tool/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $env:NUGET_API_KEY